#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running ESLint before commit..."
npm run eslint || exit 1

echo "Running tests before commit..."
npm run test || exit 1

echo "Pre-commit checks passed."
